name: "Security Scan - Secure Campus"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  semgrep:
    name: Semgrep Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Security Scan
        run: |
          semgrep scan \
            --config="p/default" \
            --config="p/nextjs" \
            --config="p/react" \
            --error \
            --text
